apiVersion: v1
kind: ConfigMap
metadata:
  name: cc-config
  namespace: content-curator
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: contentcurator
  AWS_REGION: us-east-1
  SQS_ENDPOINT: http://localstack-service:4566
  USER_ACTIVITY_QUEUE: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/user-activity
  CONTENT_INGESTED_QUEUE: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/content-ingested
  ML_SERVICE_URL: http://ml-service:5001
