apiVersion: v1
kind: Secret
metadata:
  name: cc-secrets
  namespace: content-curator
type: Opaque
stringData:
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  JWT_SECRET: content-curator-secret-key-must-be-at-least-32-characters-long
  AWS_ACCESS_KEY: test
  AWS_SECRET_KEY: test
